[package]
name = "elementary_cellular_automata"
version = "0.1.0"
authors = ["rusty shackleford <russmbiz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
num-complex = "0.3.1"